update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,4 +1,104 @@
-name: CI Pipeline
+name: CI-Pipeline
+
+on:
+  push:
+    branches: main
+  pull_request:
+    branches: main
+
+jobs:
+  Build:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Clone repo
+        uses: actions/checkout@v4
+
+      - name: Setup Go
+        uses: actions/setup-go@v5
+        with:
+          go-version: '1.21'
+
+      - name: Install dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y make
+
+      - name: Building program
+        run: make all
+        working-directory: ./src
+
+      - name: Upload binaries to artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: matrix-artifact
+          path: src/matrix
+          retention-days: 1
+
+  Test:
+    needs: Build
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: actions/download-artifact@v4
+        with:
+          name: matrix-artifact
+          path: ./src
+
+      - run: chmod +x ./src/matrix
+
+      - name: Setup Go
+        uses: actions/setup-go@v5
+        with:
+          go-version: '1.21'
+
+      - name: Install dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y make
+
+      - name: Make tests executable
+        run: chmod +x run_tests.sh test2.sh
+        working-directory: ./cicd
+
+      - name: Run tests
+        run: ./run_tests.sh
+        working-directory: ./cicd
+
+  Package:
+    needs: Test
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: actions/download-artifact@v4
+        with:
+          name: matrix-artifact
+          path: ./usr/local/bin
+
+      - name: Build deb-package
+        run: |
+          # Создаем структуру deb пакета если её нет
+          mkdir -p DEBIAN
+          
+          # Проверяем что control файл существует
+          if [ ! -f DEBIAN/control ]; then
+            echo "Error: DEBIAN/control not found!"
+            exit 1
+          fi
+          
+          # Собираем пакет
+          dpkg-deb --build . matrix.deb
+
+      - name: Upload deb package
+        uses: actions/upload-artifact@v4
+        with:
+          name: deb-package
+          path: "matrix.deb"
+          retention-days: 1name: CI Pipeline
 
 on:
   push:
